### ISSUE TITLE
PR notes 1.

### ISSUE THREAD

**Issue by thebruce** [fourkitchens/Busts#1]
**General**
During our run through there were several spots where there was cruft in the code that either doesn't work or isn't relevant - here's a pitch to removing that stuff into issues if it is something you want to work out later or removing altogether if you don't.

I offer 🤗 as encouragement to continue the good commenting effort through out.  It will be appreciated later (after a long weekend or any other disruptive time break).

**plane.swift**
Can show() and https://github.com/fourkitchens/Busts/blob/master/4K%20Busts/Plane.swift#L40 call the same code?

Does it makes sense / is it fun - to allow some variance in the color of the plane? is some sort of preference color picker hard to add?

Since you've worked out some of the physics/collision stuff - Does that open up any possibilities with these busts?

**ViewController** -

- What can you tell me about the model space for the phone view of the world with these ArKit elements? It feels like we might be missing that model for the scene data and that as a consequence the information related to the world in which i see on the phone is being stored and manipulated here in globals and other vars. We correctly have a plane model and a busts model, do we have a model for the world?  Is that sceneKit? If so would it be possible to break that out as to handle the writing to and getting of our specifics for that.

- There is a lot going on here, as you noted, it would be nice to break this up a little bit.
Does it make sense to break out the welcome alert/title screen and perhaps all user data gathering elements from the world/scene management code?

In fact - i feel like the picker should perhaps get its own model. That might ease it's transition into its own viewController with its ultimate selection data being contributed to the overall scene model.

I wonder if the alamofire download stuff might belong in the busts data model - its around data retrieval. If we delegate that to the busts model, we might then later be able to add the heads model or hands model, or w/e other elements. - perhaps that could be further abstracted into a common data fetcher, but at any case, perhaps it makes sense to not be in the controller.

Does it make sense to abstract the behaviors of the busts (follow, hello world text) into their own space away from their placement in the world/scene  (the capabilities of the bust being properties of the bust's behavior and it's placement being a property of the scene/world)?

Stupid design questions: would we consider a cartoon dialogue bubble for the texts? is that possible?  maybe that's fun. idk i want a 🍕 .

**Comment by flipactual** [comment]
## `Plane.swift`

> Can show() and https://github.com/fourkitchens/Busts/blob/master/4K%20Busts/Plane.swift#L40 call the same code?

Yes, **will do**

---

🎉 **Done!** 

> Does it makes sense / is it fun - to allow some variance in the color of the plane? is some sort of preference color picker hard to add?

I think it would be fun to make the planes a pulsing rainbow... going to punt on having a color picker there though because it doesn't further the aim of the application and would require adding additional menus (if this comes up as something that we think is neat and we'd like to do, it can be done, just punting for now as nonessential and a significant bit of work)

---

More here – cannot easily apply CIImageFilters to the planes, womp womp, still investigating rainbow gradient as I think that would be fun

---

🎉 Leaving this rabbit hole for now, but I did change this from a box to a plane for cleanness

> Since you've worked out some of the physics/collision stuff - Does that open up any possibilities with these busts?

🎉 Yes, but due to time constraints, I'm hesitant to take that on _right now_

**Comment by flipactual** [comment]
## `ViewController.swift`

> What can you tell me about the model space for the phone view of the world with these ArKit elements? It feels like we might be missing that model for the scene data and that as a consequence the information related to the world in which i see on the phone is being stored and manipulated here in globals and other vars. We correctly have a plane model and a busts model, do we have a model for the world? Is that sceneKit? If so would it be possible to break that out as to handle the writing to and getting of our specifics for that.

🎉 ARKit and SceneKit handle (aspects of) the model of the world for us. We could split our model of that world out more, but I'm not sure how much we'd want to. There are definitely cases for it, like having a class for `Plane`s etc., but I'm uncertain how far that extends

> There is a lot going on here, as you noted, it would be nice to break this up a little bit.
Does it make sense to break out the welcome alert/title screen and perhaps all user data gathering elements from the world/scene management code?

I think so. I'm uncertain how to do this, but I think it's worth figuring out sooner than later, so I **will investigate**

> In fact - i feel like the picker should perhaps get its own model. That might ease it's transition into its own viewController with its ultimate selection data being contributed to the overall scene model.

I _think_ I agree, **will investigate**

---

🎉 **Did it**... sloppily

But it's a step in the right direction at least

> I wonder if the alamofire download stuff might belong in the busts data model - its around data retrieval. If we delegate that to the busts model, we might then later be able to add the heads model or hands model, or w/e other elements. - perhaps that could be further abstracted into a common data fetcher, but at any case, perhaps it makes sense to not be in the controller.

**Will do**, I'll see how much I can improve this without piling on work

> Does it make sense to abstract the behaviors of the busts (follow, hello world text) into their own space away from their placement in the world/scene (the capabilities of the bust being properties of the bust's behavior and it's placement being a property of the scene/world)?

Perhaps a first step here would be to make the `Bust` struct responsible for providing the composed `SCNNode`. And then doing something similar with the text. Or have them extend the same base class. **Will try**

> Stupid design questions: would we consider a cartoon dialogue bubble for the texts? is that possible? maybe that's fun. idk i want a 🍕 .

🎉 Perhaps! I think we'd have to do the whole bounding box thing for the text, but why not. Should raise in #vr Slack channel

**Comment by flipactual** [comment]
> Does it makes sense / is it fun - to allow some variance in the color of the plane? is some sort of preference color picker hard to add?

More here – cannot easily apply CIImageFilters to the planes, womp womp, still investigating rainbow gradient as I think that would be fun

**Comment by flipactual** [comment]
Closing in favor of #4, #5, and #6
